name: Build and publish Maven package

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Deploy Maven to GitHub Packages
      run: mvn --batch-mode deploy -DGITHUB_OWNER=${GITHUB_REPO_OWNER} --file pom.xml`
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPO_OWNER: ${{ github.event.repository_owner }}