name: Build and publish Maven package

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Deploy Maven to GitHub Packages
      run: mvn --batch-mode deploy -DGITHUB_OWNER=${GITHUB_REPO_OWNER}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPO_OWNER: ${{ github.event.repository_owner }}
